# git clone git://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard.git
# cd ~/tmux-MacOSX-pasteboard
# make reattach-to-user-namespace
# cp reattach-to-user-namespace ~/bin

#クリップボードの共有
set-option -g default-command "~/bin/reattach-to-user-namespace -l $SHELL"

#C-cでコピー
bind-key C-c run "tmux save-buffer - | ~/bin/reattach-to-user-namespace pbcopy"

#C-vで貼り付け
bind-key C-v run "~/bin/reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"

# vim:set ft=tmux:

